### ISSUE TITLE
Building for CC2652 \ 1352

### ISSUE THREAD

**Issue by atxbyea** [openthread/ot-cc13x2-cc26x2#421]
**Describe the bug** A clear and concise description of what the bug is.
Building firmware per the readme does not longer work it seems, readme is from 2021.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

Try to build firmware based on steps outlined in the readme file for 1352 \ 2652

https://github.com/openthread/ot-cc13x2-cc26x2/blob/main/src/cc2652/README.md

**Expected behavior** A clear and concise description of what you expected to happen.

Firmware to be built, however it fails

**Console/log output** If applicable, add console/log output to help explain your problem.
``
    OPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=openthread-core-cc1352-config-check.h
    [729/730] Linking CXX executable bin/ot-ncp-ftd
    FAILED: bin/ot-ncp-ftd 
    : && /usr/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -fdata-sections -ffunction-sections -fno-exceptions -fno-rtti -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -fdata-sections -ffunction-sections -nostartfiles -specs=nano.specs -specs=nosys.specs -Wl,-Map=map.map openthread/examples/apps/ncp/CMakeFiles/ot-ncp-ftd.dir/main.c.obj openthread/examples/apps/ncp/CMakeFiles/ot-ncp-ftd.dir/ncp.c.obj -o bin/ot-ncp-ftd  lib/libopenthread-ncp-ftd.a  lib/libopenthread-cc1352.a  lib/libopenthread-ftd.a  lib/libopenthread-cc1352.a  lib/libopenthread-ncp-ftd.a  lib/libmbedtls.a  lib/libopenthread-ftd.a  lib/libtcplp-ftd.a  lib/libopenthread-ftd.a  lib/libtcplp-ftd.a  lib/libmbedtls.a  lib/libmbedx509.a  lib/libopenthread-hdlc.a  lib/libopenthread-spinel-ncp.a  ../third_party/ti/devices/cc13x2_cc26x2/driverlib/bin/gcc/driverlib.a  -T/home/eirikz/matter/openthread/third_party/ti/devices/cc13x2_cc26x2/linker_files/cc26x2r1f.lds  -Wl,--gc-sections  -Wl,-Map=ot-ncp-ftd.map  lib/libmbedcrypto.a && :
    /usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: bin/ot-ncp-ftd section `.text' will not fit in region `FLASH'
    /usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: section .ccfg LMA [0000000000057fa8,0000000000057fff] overlaps section .text LMA [0000000000000000,0000000000076997]
    /usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 125780 bytes
    collect2: error: ld returned 1 exit status
    [730/730] Linking CXX executable bin/ot-cli-ftd
    FAILED: bin/ot-cli-ftd 
    : && /usr/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -fdata-sections -ffunction-sections -fno-exceptions -fno-rtti -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -fdata-sections -ffunction-sections -nostartfiles -specs=nano.specs -specs=nosys.specs -Wl,-Map=map.map openthread/examples/apps/cli/CMakeFiles/ot-cli-ftd.dir/cli_uart.cpp.obj openthread/examples/apps/cli/CMakeFiles/ot-cli-ftd.dir/main.c.obj -o bin/ot-cli-ftd  lib/libopenthread-cli-ftd.a  lib/libopenthread-cc1352.a  lib/libopenthread-ftd.a  lib/libopenthread-cc1352.a  lib/libopenthread-cli-ftd.a  lib/libmbedtls.a  lib/libopenthread-ftd.a  lib/libtcplp-ftd.a  lib/libopenthread-ftd.a  lib/libtcplp-ftd.a  lib/libmbedtls.a  lib/libmbedx509.a  ../third_party/ti/devices/cc13x2_cc26x2/driverlib/bin/gcc/driverlib.a  -T/home/eirikz/matter/openthread/third_party/ti/devices/cc13x2_cc26x2/linker_files/cc26x2r1f.lds  -Wl,--gc-sections  -Wl,-Map=ot-cli-ftd.map  lib/libmbedcrypto.a && :
    /usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: bin/ot-cli-ftd section `.text' will not fit in region `FLASH'
    /usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: section .ccfg LMA [0000000000057fa8,0000000000057fff] overlaps section .text LMA [0000000000000000,000000000007a557]
    /usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 141076 bytes
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
``
**Additional context** Add any other context about the problem here.
https://dpaste.org/0mWi7

**Comment by jwhui** [comment]
I just checked out the latest and successfully ran the following command:
```
./script/build -DTI_PLATFORM=cc2652
```

The GitHub Actions build checks are also passing: https://github.com/openthread/ot-cc13x2-cc26x2/actions
